name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
      - 'middleware/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'middleware/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./middleware
      run: npm install

    - name: Run tests
      working-directory: ./middleware
      run: npm test

    # Conditional step after tests
    - name: Notify success
      if: success()
      run: echo "Tests passed successfully!"
      # You can also use other actions for Slack notifications, etc.

    - name: Notify failure
      if: failure()
      run: echo "Tests failed!"
      # Similar, can notify through various channels or take other actions
